NAME=BuntyShrutiPhotoFrame
SLIDE_INTERVAL=20
RELOAD_INTERVAL=4200
PHOTO_DIR=/home/pi/Pictures/Slides/feh/landscape
#Shows datetime at the lower left side of the screen
SHOW_DATE=1
#Shows file index at the lower left side of the screen
SHOW_INDEX=1
LOGFILE=/home/pi/slideshow/slideshow.log
